const actions = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_SIGNUP: 'USER_SIGNUP',
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',

  // JOB ACTION
  UPLOAD_POST: 'UPLOAD_POST',
  UPLOAD_POST_SUCCESS: 'UPLOAD_POST_SUCCESS',
  GET_ALL_JOB: 'GET_ALL_JOB',
  GET_ALL_JOB_SUCCESS: 'GET_ALL_JOB_SUCCESS',
  DELETE_JOB: 'DELETE_JOB',
  EDIT_JOB: 'EDIT_JOB',
  EDIT_JOB_SUCCESS: 'EDIT_JOB_SUCCESS',

  // GET INFO USER
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  DELET_USER_INFO: 'DELET_USER_INFO',
  EDIT_USER: 'EDIT_USER',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',

  // GET ACCOUNT
  GET_LIST_USER: 'GET_LIST_USER',
  GET_LIST_USER_SUCCESS: 'GET_LIST_USER_SUCCESS',
  GET_LIST_USER_REC: 'GET_LIST_USER_REC',
  GET_LIST_USER_REC_SUCCESS: 'GET_LIST_USER_REC_SUCCESS',
  FILTER_USER: "FILTER_USER",
  FILTER_USER_USERNAME: 'FILTER_USER_USERNAME',

  // GET LIST RECRUITMENT
  GET_LIST_RECRUITMENT: 'GET_LIST_RECRUITMENT',
  GET_LIST_RECRUITMENT_SUCCESS: 'GET_LIST_RECRUITMENT_SUCCESS',

  // VERIFY CANDIDATE
  VERIFY_CANDIDATE: 'VERIFY_CANDIDATE',
  VERIFY_CANDIDATE_SUCCESS: 'VERIFY_CANDIDATE_SUCCESS',

  // FeedBack Job
  APPROVE_TO_JOB: 'APPROVE_TO_JOB',
  APPROVE_TO_JOB_SUCCESS: 'APPROVE_TO_JOB_SUCCESS',
  REJECT_TO_JOB: 'REJECT_TO_JOB',
  REJECT_TO_JOB_SUCCESS: 'REJECT_TO_JOB_SUCCESS',
  APPLY_TO_JOB: 'APPLY_TO_JOB',
  APPLY_TO_JOB_SUCCESS: 'APPLY_TO_JOB_SUCCESS',

  // Checkout
  ADD_COINS: 'ADD_COINS',
  UPGRADE_VIP: 'UPGRADE_VIP',
  REMOVE_COINS: 'REMOVE_COINS',

  // Products 
  GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
  GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",

  // Get list categories
  GET_LIST_CATEGORIES: 'GET_LIST_CATEGORIES',
  SEARCH_LIST_CATEGORIES: 'SEARCH_LIST_CATEGORIES',
  GET_LIST_CATEGORIES_SUCCESS: 'GET_LIST_CATEGORIES_SUCCESS',
  EDIT_CATEGORIES: 'EDIT_CATEGORIES',
  ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  PAGINATION_DATA: 'PAGINATION_DATA',

  // ADD_CART: 'ADD_CART',
  // GET_CART: 'GET_CART',
  // REMOVE_CART: 'REMOVE_CART',
  // UPDATE_CART: 'UPDATE_CART',
  // CLEAR_CART: 'CLEAR_CART',
  // GET BRANCH

  GET_ALL_COLOR: "GET_ALL_COLOR",
  GET_ALL_COLOR_SUCCESS: "GET_ALL_COLOR_SUCCESS",
  GET_ALL_SIZE: "GET_ALL_SIZE",
  GET_ALL_SIZE_SUCCESS: "GET_ALL_SIZE_SUCCESS",
  EDIT_SIZE_SUCCESS: "EDIT_SIZE_SUCCESS",
  UPLOADS_SUCCESS: "UPLOADS_SUCCESS",
  UPLOADS_FILES: "UPLOADS_FILES",

  EDIT_SIZE: "EDIT_SIZE",
  REMOVE_SIZE: "REMOVE_SIZE",
  ADD_SIZE: "ADD_SIZE",

  EDIT_COLOR: "EDIT_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  ADD_COLOR: "ADD_COLOR",

  GET_ALL_CONTACT: "GET_ALL_CONTACT",
  GET_LIST_CONTACT_SUCCESS: "GET_LIST_CONTACT_SUCCESS",
  EDIT_CONTACT: "EDIT_CONTACT",
  REMOVE_CONTACT: "REMOVE_CONTACT",
  ADD_CONTACT: "ADD_CONTACT",

  GET_ALL_CUSTOMER: "GET_ALL_CUSTOMER",
  GET_LIST_CUSTOMER_SUCCESS: "GET_LIST_CUSTOMER_SUCCESS",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  REMOVE_CUSTOMER: "REMOVE_CUSTOMER",
  ADD_CUSTOMER: "ADD_CUSTOMER",

  GET_ALL_ORDER: "GET_ALL_ORDER",
  GET_LIST_ORDER_SUCCESS: "GET_LIST_ORDER_SUCCESS",
  EDIT_ORDER: "EDIT_ORDER",
  REMOVE_ORDER: "REMOVE_ORDER",
  ADD_ORDER: "ADD_ORDER",
  GET_DETAIL_ORDER: "GET_DETAIL_ORDER",
  GET_DETAIL_ORDER_SUCCESS: "GET_DETAIL_ORDER_SUCCESS",
  ADD_ORDER_CHECKOUT: "ADD_ORDER_CHECKOUT",

  GET_ACCOUNT: "GET_ACCOUNT",
  GET_ACCOUNT_SUCCESS: "GET_ACCOUNT_SUCCESS",
  GET_ACCOUNT_ERROR: "GET_ACCOUNT_ERROR",

  GET_ALL_BLOG: "GET_ALL_BLOG",
  GET_LIST_BLOG_SUCCESS: "GET_LIST_BLOG_SUCCESS",
  EDIT_BLOG: "EDIT_BLOG",
  REMOVE_BLOG: "REMOVE_BLOG",
  ADD_BLOG: "ADD_BLOG",
  GET_DETAIL_BLOG: "GET_DETAIL_BLOG",

  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
  ADD_ONE_ITEM_CART: "ADD_ONE_ITEM_CART",
  REMOVE_ONE_ITEM_CART: "REMOVE_ONE_ITEM_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
  ADD_ONE_ITEM_CART: "ADD_ONE_ITEM_CART",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",
  REMOVE_ONE_ITEM_CART: "REMOVE_ONE_ITEM_CART",
  CHANGE_STATUS_CHECKOUT: "CHANGE_STATUS_CHECKOUT",

  TOGGLE_MENU: "TOGGLE_MENU",

  SHOW_LOADING: 'GLOBAL_SHOW_LOADING',
  HIDE_LOADING: 'GLOBAL_HIDE_LOADING',
  SHOW_SIDEBAR: 'SHOW_SIDEBAR',
  HIDE_SIDEBAR: 'HIDE_SIDEBAR',

  // brands
  GET_LIST_BRANDS: 'GET_LIST_BRANDS',
  SEARCH_LIST_BRANDS: 'SEARCH_LIST_BRANDS',
  GET_LIST_BRANDS_SUCCESS: 'GET_LIST_BRANDS_SUCCESS',
  EDIT_BRANDS: 'EDIT_BRANDS',
  ADD_NEW_BRAND: 'ADD_NEW_BRAND',
  DELETE_BRAND: 'DELETE_BRAND',

  // slide
  GET_LIST_SLIDES: 'GET_LIST_SLIDES',
  SEARCH_LIST_SLIDES: 'SEARCH_LIST_SLIDES',
  GET_LIST_SLIDES_SUCCESS: 'GET_LIST_SLIDES_SUCCESS',
  EDIT_SLIDES: 'EDIT_SLIDES',
  ADD_NEW_SLIDE: 'ADD_NEW_SLIDE',
  DELETE_SLIDE: 'DELETE_SLIDE',

  // branch
  GET_LIST_BRANCHES: 'GET_LIST_BRANCHES',
  SEARCH_LIST_BRANCHES: 'SEARCH_LIST_BRANCHES',
  GET_LIST_BRANCHES_SUCCESS: 'GET_LIST_BRANCHES_SUCCESS',
  EDIT_BRANCH: 'EDIT_BRANCH',
  ADD_NEW_BRANCH: 'ADD_NEW_BRANCH',
  DELETE_BRANCH: 'DELETE_BRANCH',

  // warehouse
  GET_LIST_WAREHOUSES: 'GET_LIST_WAREHOUSES',
  SEARCH_LIST_WAREHOUSES: 'SEARCH_LIST_WAREHOUSES',
  GET_LIST_WAREHOUSES_SUCCESS: 'GET_LIST_WAREHOUSES_SUCCESS',
  EDIT_WAREHOUSE: 'EDIT_WAREHOUSE',
  ADD_NEW_WAREHOUSE: 'ADD_NEW_WAREHOUSE',
  DELETE_WAREHOUSE: 'DELETE_WAREHOUSE',
}
export default actions;